// flow-typed signature: 4ee4af1ba27ad4be2d821c833b30486f
// flow-typed version: <<STUB>>/cluster_v^0.7.7/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cluster'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cluster' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cluster/examples/app-cluster' {
  declare module.exports: any;
}

declare module 'cluster/examples/app' {
  declare module.exports: any;
}

declare module 'cluster/examples/basic' {
  declare module.exports: any;
}

declare module 'cluster/examples/cli-app' {
  declare module.exports: any;
}

declare module 'cluster/examples/cli' {
  declare module.exports: any;
}

declare module 'cluster/examples/connect' {
  declare module.exports: any;
}

declare module 'cluster/examples/debug' {
  declare module.exports: any;
}

declare module 'cluster/examples/envs' {
  declare module.exports: any;
}

declare module 'cluster/examples/error' {
  declare module.exports: any;
}

declare module 'cluster/examples/express' {
  declare module.exports: any;
}

declare module 'cluster/examples/logger' {
  declare module.exports: any;
}

declare module 'cluster/examples/pids' {
  declare module.exports: any;
}

declare module 'cluster/examples/reload' {
  declare module.exports: any;
}

declare module 'cluster/examples/repl-unix' {
  declare module.exports: any;
}

declare module 'cluster/examples/repl' {
  declare module.exports: any;
}

declare module 'cluster/examples/single' {
  declare module.exports: any;
}

declare module 'cluster/examples/standalone' {
  declare module.exports: any;
}

declare module 'cluster/examples/tcp' {
  declare module.exports: any;
}

declare module 'cluster/examples/unix' {
  declare module.exports: any;
}

declare module 'cluster/examples/vhost' {
  declare module.exports: any;
}

declare module 'cluster/lib/cluster' {
  declare module.exports: any;
}

declare module 'cluster/lib/master' {
  declare module.exports: any;
}

declare module 'cluster/lib/mixins/receiver' {
  declare module.exports: any;
}

declare module 'cluster/lib/plugins/cli' {
  declare module.exports: any;
}

declare module 'cluster/lib/plugins/debug' {
  declare module.exports: any;
}

declare module 'cluster/lib/plugins/logger' {
  declare module.exports: any;
}

declare module 'cluster/lib/plugins/pidfiles' {
  declare module.exports: any;
}

declare module 'cluster/lib/plugins/reload' {
  declare module.exports: any;
}

declare module 'cluster/lib/plugins/repl' {
  declare module.exports: any;
}

declare module 'cluster/lib/plugins/stats' {
  declare module.exports: any;
}

declare module 'cluster/lib/utils' {
  declare module.exports: any;
}

declare module 'cluster/lib/worker' {
  declare module.exports: any;
}

declare module 'cluster/test/common' {
  declare module.exports: any;
}

declare module 'cluster/test/support/all' {
  declare module.exports: any;
}

declare module 'cluster/test/support/exported' {
  declare module.exports: any;
}

declare module 'cluster/test/support/server' {
  declare module.exports: any;
}

declare module 'cluster/test/support/standalone' {
  declare module.exports: any;
}

declare module 'cluster/test/test.basic' {
  declare module.exports: any;
}

declare module 'cluster/test/test.cli-status' {
  declare module.exports: any;
}

declare module 'cluster/test/test.dns' {
  declare module.exports: any;
}

declare module 'cluster/test/test.env' {
  declare module.exports: any;
}

declare module 'cluster/test/test.ephemeral' {
  declare module.exports: any;
}

declare module 'cluster/test/test.filename' {
  declare module.exports: any;
}

declare module 'cluster/test/test.logger.custom-path' {
  declare module.exports: any;
}

declare module 'cluster/test/test.logger' {
  declare module.exports: any;
}

declare module 'cluster/test/test.pidfiles' {
  declare module.exports: any;
}

declare module 'cluster/test/test.restart-env' {
  declare module.exports: any;
}

declare module 'cluster/test/test.restart' {
  declare module.exports: any;
}

declare module 'cluster/test/test.shutdown-all' {
  declare module.exports: any;
}

declare module 'cluster/test/test.shutdown' {
  declare module.exports: any;
}

declare module 'cluster/test/test.standalone-shutdown' {
  declare module.exports: any;
}

declare module 'cluster/test/test.standalone.file' {
  declare module.exports: any;
}

declare module 'cluster/test/test.standalone' {
  declare module.exports: any;
}

declare module 'cluster/test/test.standalone.restart' {
  declare module.exports: any;
}

declare module 'cluster/test/test.worker-kill' {
  declare module.exports: any;
}

declare module 'cluster/test/test.worker-quit-keep-alive' {
  declare module.exports: any;
}

declare module 'cluster/test/test.worker-quit' {
  declare module.exports: any;
}

declare module 'cluster/test/test.worker-term' {
  declare module.exports: any;
}

declare module 'cluster/test/test.working-dir' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cluster/examples/app-cluster.js' {
  declare module.exports: $Exports<'cluster/examples/app-cluster'>;
}
declare module 'cluster/examples/app.js' {
  declare module.exports: $Exports<'cluster/examples/app'>;
}
declare module 'cluster/examples/basic.js' {
  declare module.exports: $Exports<'cluster/examples/basic'>;
}
declare module 'cluster/examples/cli-app.js' {
  declare module.exports: $Exports<'cluster/examples/cli-app'>;
}
declare module 'cluster/examples/cli.js' {
  declare module.exports: $Exports<'cluster/examples/cli'>;
}
declare module 'cluster/examples/connect.js' {
  declare module.exports: $Exports<'cluster/examples/connect'>;
}
declare module 'cluster/examples/debug.js' {
  declare module.exports: $Exports<'cluster/examples/debug'>;
}
declare module 'cluster/examples/envs.js' {
  declare module.exports: $Exports<'cluster/examples/envs'>;
}
declare module 'cluster/examples/error.js' {
  declare module.exports: $Exports<'cluster/examples/error'>;
}
declare module 'cluster/examples/express.js' {
  declare module.exports: $Exports<'cluster/examples/express'>;
}
declare module 'cluster/examples/logger.js' {
  declare module.exports: $Exports<'cluster/examples/logger'>;
}
declare module 'cluster/examples/pids.js' {
  declare module.exports: $Exports<'cluster/examples/pids'>;
}
declare module 'cluster/examples/reload.js' {
  declare module.exports: $Exports<'cluster/examples/reload'>;
}
declare module 'cluster/examples/repl-unix.js' {
  declare module.exports: $Exports<'cluster/examples/repl-unix'>;
}
declare module 'cluster/examples/repl.js' {
  declare module.exports: $Exports<'cluster/examples/repl'>;
}
declare module 'cluster/examples/single.js' {
  declare module.exports: $Exports<'cluster/examples/single'>;
}
declare module 'cluster/examples/standalone.js' {
  declare module.exports: $Exports<'cluster/examples/standalone'>;
}
declare module 'cluster/examples/tcp.js' {
  declare module.exports: $Exports<'cluster/examples/tcp'>;
}
declare module 'cluster/examples/unix.js' {
  declare module.exports: $Exports<'cluster/examples/unix'>;
}
declare module 'cluster/examples/vhost.js' {
  declare module.exports: $Exports<'cluster/examples/vhost'>;
}
declare module 'cluster/index' {
  declare module.exports: $Exports<'cluster'>;
}
declare module 'cluster/index.js' {
  declare module.exports: $Exports<'cluster'>;
}
declare module 'cluster/lib/cluster.js' {
  declare module.exports: $Exports<'cluster/lib/cluster'>;
}
declare module 'cluster/lib/master.js' {
  declare module.exports: $Exports<'cluster/lib/master'>;
}
declare module 'cluster/lib/mixins/receiver.js' {
  declare module.exports: $Exports<'cluster/lib/mixins/receiver'>;
}
declare module 'cluster/lib/plugins/cli.js' {
  declare module.exports: $Exports<'cluster/lib/plugins/cli'>;
}
declare module 'cluster/lib/plugins/debug.js' {
  declare module.exports: $Exports<'cluster/lib/plugins/debug'>;
}
declare module 'cluster/lib/plugins/logger.js' {
  declare module.exports: $Exports<'cluster/lib/plugins/logger'>;
}
declare module 'cluster/lib/plugins/pidfiles.js' {
  declare module.exports: $Exports<'cluster/lib/plugins/pidfiles'>;
}
declare module 'cluster/lib/plugins/reload.js' {
  declare module.exports: $Exports<'cluster/lib/plugins/reload'>;
}
declare module 'cluster/lib/plugins/repl.js' {
  declare module.exports: $Exports<'cluster/lib/plugins/repl'>;
}
declare module 'cluster/lib/plugins/stats.js' {
  declare module.exports: $Exports<'cluster/lib/plugins/stats'>;
}
declare module 'cluster/lib/utils.js' {
  declare module.exports: $Exports<'cluster/lib/utils'>;
}
declare module 'cluster/lib/worker.js' {
  declare module.exports: $Exports<'cluster/lib/worker'>;
}
declare module 'cluster/test/common.js' {
  declare module.exports: $Exports<'cluster/test/common'>;
}
declare module 'cluster/test/support/all.js' {
  declare module.exports: $Exports<'cluster/test/support/all'>;
}
declare module 'cluster/test/support/exported.js' {
  declare module.exports: $Exports<'cluster/test/support/exported'>;
}
declare module 'cluster/test/support/server.js' {
  declare module.exports: $Exports<'cluster/test/support/server'>;
}
declare module 'cluster/test/support/standalone.js' {
  declare module.exports: $Exports<'cluster/test/support/standalone'>;
}
declare module 'cluster/test/test.basic.js' {
  declare module.exports: $Exports<'cluster/test/test.basic'>;
}
declare module 'cluster/test/test.cli-status.js' {
  declare module.exports: $Exports<'cluster/test/test.cli-status'>;
}
declare module 'cluster/test/test.dns.js' {
  declare module.exports: $Exports<'cluster/test/test.dns'>;
}
declare module 'cluster/test/test.env.js' {
  declare module.exports: $Exports<'cluster/test/test.env'>;
}
declare module 'cluster/test/test.ephemeral.js' {
  declare module.exports: $Exports<'cluster/test/test.ephemeral'>;
}
declare module 'cluster/test/test.filename.js' {
  declare module.exports: $Exports<'cluster/test/test.filename'>;
}
declare module 'cluster/test/test.logger.custom-path.js' {
  declare module.exports: $Exports<'cluster/test/test.logger.custom-path'>;
}
declare module 'cluster/test/test.logger.js' {
  declare module.exports: $Exports<'cluster/test/test.logger'>;
}
declare module 'cluster/test/test.pidfiles.js' {
  declare module.exports: $Exports<'cluster/test/test.pidfiles'>;
}
declare module 'cluster/test/test.restart-env.js' {
  declare module.exports: $Exports<'cluster/test/test.restart-env'>;
}
declare module 'cluster/test/test.restart.js' {
  declare module.exports: $Exports<'cluster/test/test.restart'>;
}
declare module 'cluster/test/test.shutdown-all.js' {
  declare module.exports: $Exports<'cluster/test/test.shutdown-all'>;
}
declare module 'cluster/test/test.shutdown.js' {
  declare module.exports: $Exports<'cluster/test/test.shutdown'>;
}
declare module 'cluster/test/test.standalone-shutdown.js' {
  declare module.exports: $Exports<'cluster/test/test.standalone-shutdown'>;
}
declare module 'cluster/test/test.standalone.file.js' {
  declare module.exports: $Exports<'cluster/test/test.standalone.file'>;
}
declare module 'cluster/test/test.standalone.js' {
  declare module.exports: $Exports<'cluster/test/test.standalone'>;
}
declare module 'cluster/test/test.standalone.restart.js' {
  declare module.exports: $Exports<'cluster/test/test.standalone.restart'>;
}
declare module 'cluster/test/test.worker-kill.js' {
  declare module.exports: $Exports<'cluster/test/test.worker-kill'>;
}
declare module 'cluster/test/test.worker-quit-keep-alive.js' {
  declare module.exports: $Exports<'cluster/test/test.worker-quit-keep-alive'>;
}
declare module 'cluster/test/test.worker-quit.js' {
  declare module.exports: $Exports<'cluster/test/test.worker-quit'>;
}
declare module 'cluster/test/test.worker-term.js' {
  declare module.exports: $Exports<'cluster/test/test.worker-term'>;
}
declare module 'cluster/test/test.working-dir.js' {
  declare module.exports: $Exports<'cluster/test/test.working-dir'>;
}
